---
- name: Install apt HTTPS transport
  package:
    name:
      - apt-transport-https
    state: present

- name: Create apt key directory
  file:
    path: "{{ docker_apt_key_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  when: docker_manage_apt_key_dir and not docker_remove

- name: Add apt keys
  ansible.builtin.get_url:
    url: "{{ docker_apt_key_url }}"
    dest: "{{ docker_apt_key_dir }}/docker.key"
    checksum: "{{ docker_apt_key_checksum }}"
    owner: root
    group: root
    mode: "0644"
  when: not docker_remove

- name: Add apt repositories
  template:
    src: docker.list.j2
    dest: /etc/apt/sources.list.d/docker.list
    owner: root
    group: root
    mode: "0644"
  vars:
    apt_key_dir: "{{ docker_apt_key_dir }}"
    arch: "{{ docker_apt_arch_map[ansible_architecture] | default(ansible_architecture) }}"
  register: docker_apt_added
  when: not docker_remove

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  when: docker_apt_added.changed and not docker_remove
